Feature testing with Hound

diff --git a/bin/ci b/bin/ci
--- a/bin/ci
+++ b/bin/ci
@@ -1,9 +1,20 @@
 #!/usr/bin/env bash
 
-echo Running tests...
+# Exit on any nonzero exit code (error)
+set -e
 
-mix deps.get && mix test && npm install && npm test &&
-cd examples/example-phx-1_2 && mix deps.get && mix test &&
-cd ../example-phx-1_3 && mix deps.get && mix test &&
-npm install && npm install -g phantomjs-prebuilt && npm test &&
-cd -
+echo 💡  Running tests...
+
+mix test
+
+cd ./examples/example-phx-1_2
+mix deps.get
+mix test
+
+cd ../example-phx-1_3
+mix deps.get
+nohup chromedriver &
+mix test
+killall chromedriver
+
+echo ✅  Tests complete
